%NS.PROCESS%

 IF SUBSTR(IL,1,11)="XRAY ID: NS" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"XRAY ND END FLAG" THEN
    IF XRAY.GROUP#"ERROR MODE" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," UNEXPECTED XRAY NS ID",@CR,
        "XRAY GROUP=",XRAY.GROUP,@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET XRAY.GROUP="XRAY NS ID"
    ADD 1 TO XRAY.EXTRACTION.ID
    LET NSOL=""
    LET NSOL=SUBSTR(IL,13,4)+SUBSTR(IL,18,6)+SUBSTR(IL,25,4)
    LET EXTRACTION.KEY=SUBSTR(IL,13,16)+XRAY.EXTRACTION.ID AS "5C"
    IF SUBSTR(IL,13,4) IS NOT NODE
       THEN BEGIN
            PRINT TO NS.ERROR.FILE
             RECORD.NUMBER," BAD NODE NUMBER IN XRAY NS ID",@CR
            LET XRAY.GROUP="ERROR MODE"
            FINISH THIS.RECORD
            END
       ELSE LET NODE=SUBSTR(IL,13,4) AS NODE
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,16)="XRAY NS END FLAG" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP="MAX(CS)" THEN
       LET NSOL1=TRIM(NSOL1)+"   0   0   0"
     ELSE
    IF XRAY.GROUP#"NS END FLAG PENDING" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," UNEXPECTED NS END FLAG",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET XRAY.GROUP="XRAY NS END FLAG"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,4)="EXCT" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"XRAY NS ID" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," UNEXPECTED EXCT GROUP",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET XRAY.GROUP="EXCT"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,3)="RMK" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"EXCT" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," UNEXPECTED RMK GROUP",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET XRAY.GROUP="RMK"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,10)="NODE LINKS" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"RMK" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED NODE LINKS GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="NODE LINKS"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,5)="ASYNC" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"NODE LINKS" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED ASYNC GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="ASYNC"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,7)="PRINTER" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"ASYNC" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED PRINTER GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="PRINTER"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,10)="CODE DELAY" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"PRINTER" THEN
     IF XRAY.GROUP="NODE LINKS" THEN
        BEGIN
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        LET NSOL=TRIM(NSOL)+"       0"
        END
     ELSE IF XRAY.GROUP="ASYNC" THEN
             BEGIN
             LET NSOL=TRIM(NSOL)+"       0"
             LET NSOL=TRIM(NSOL)+"       0"
             LET NSOL=TRIM(NSOL)+"       0"
             LET NSOL=TRIM(NSOL)+"       0"
             END
    ELSE
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED CODE DELAY GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="CODE DELAY"
    FINISH THIS.RECORD
    END

   IF SUBSTR(IL,1,7)="PROCESS" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"CODE DELAY" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED PROCESS GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     IF SUBSTR(IL,10,5)="ASYNC"
        THEN LET ASYNC="YES"
        ELSE LET ASYNC="NO"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="PROCESS"
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,7)="PERCENT" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"PROCESS" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED PERCENT GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="PERCENT"
    IF ASYNC="YES" THEN
    BEGIN
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,12,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,18,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,24,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,30,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,36,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,42,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,48,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,54,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,60,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,66,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,72,2)
    END
    ELSE
    BEGIN
    LET NSOL=TRIM(NSOL)+"00"
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,12,2)
    LET NSOL=TRIM(NSOL)+"00"
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,18,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,24,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,30,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,36,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,42,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,48,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,54,2)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,60,2)
    END
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,7)="MAX(MS)" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"PERCENT" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED MAX(CS) GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="MAX(CS)"
    IF ASYNC="YES" THEN
    BEGIN
    LET NSOL1=SUBSTR(IL,10,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,16,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,22,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,28,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,34,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,40,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,46,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,52,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,58,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,64,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,70,4)
    END
    ELSE
    BEGIN
    LET NSOL1="0000"
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,10,4)
    LET NSOL1=TRIM(NSOL1)+"0000"
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,16,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,22,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,28,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,34,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,40,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,46,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,52,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,58,4)
    END
    FINISH THIS.RECORD
    END

 IF SUBSTR(IL,1,7)="AVERAGE" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF XRAY.GROUP#"MAX(CS)" THEN
     BEGIN
     PRINT TO NS.ERROR.FILE
      RECORD.NUMBER," UNEXPECTED AVERAGE GROUP",@CR
     LET XRAY.GROUP="ERROR MODE"
     FINISH THIS.RECORD
     END
    LET XRAY.GROUP="NS END FLAG PENDING"
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,27,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,43,4)
    LET NSOL1=TRIM(NSOL1)+SUBSTR(IL,60,4)
    FINISH THIS.RECORD
    END

 IF XRAY.GROUP="EXCT" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,4) IS NOT "4N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," EXCT ERROR",@CR
      LET XRAY.GROUP="ERROR MODE"
      FINISH THIS.RECORD
      END
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,7,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,13,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,19,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,25,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,31,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,37,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,43,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,49,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,55,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,61,4)
    FINISH THIS.RECORD
    END

 IF XRAY.GROUP="RMK" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,8) IS NOT "8N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," RMK ERROR",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,8)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,10,8)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,19,8)
    FINISH THIS.RECORD
    END

 IF XRAY.GROUP="NODE LINKS" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,4)="CPSO" THEN
       FINISH THIS.RECORD
    IF SUBSTR(IL,1,8) IS NOT "8N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," NODE LINKS ERROR",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,10,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,19,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,28,8)
     FINISH THIS.RECORD
     END

 IF XRAY.GROUP="ASYNC" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,4)="CPSO" THEN
       FINISH THIS.RECORD
    IF SUBSTR(IL,1,8) IS NOT "8N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," ASYNC ERROR",@CR
       FINISH THIS.RECORD
       END
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,8)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,10,8)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,19,8)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,28,8)
    FINISH THIS.RECORD
    END

 IF XRAY.GROUP="PRINTER" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,4)="CPSO" THEN
       FINISH THIS.RECORD
    IF SUBSTR(IL,1,8) IS NOT "8N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," PRINTER ERROR",@CR
       LET XRAY.GROUP="ERROR MODE"
       END
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,10,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,19,8)
     LET NSOL=TRIM(NSOL)+SUBSTR(IL,28,8)
     FINISH THIS.RECORD
     END

 IF XRAY.GROUP="CODE DELAY" THEN
    BEGIN
    LET ACCOUNTED.FOR="YES"
    IF SUBSTR(IL,1,4) IS NOT "4N" THEN
       BEGIN
       PRINT TO NS.ERROR.FILE
        RECORD.NUMBER," CODE DELAY ERROR",@CR
       LET XRAY.GROUP="ERROR MODE"
       FINISH THIS.RECORD
       END
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,1,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,15,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,29,4)
    LET NSOL=TRIM(NSOL)+SUBSTR(IL,43,4)
    FINISH THIS.RECORD
    END

   