
 
 
 
 
 
 
 
 
                               P C - N T R A C K
 
                             STARTUP DOCUMENTATION
                                DECEMBER, 1988
                                 JO ANN JOELS
 
 
         THIS DOCUMENTATION IS BEING PROVIDED TO HELP YOU GET STARTED USING 
         PC-NTRACK.  THIS DOCUMENTATION IS NOT INTENDED TO ANSWER ALL OF YOUR 
         QUESTIONS BUT JUST TO ENABLE YOU TO START USING THE PROGRAM.  
         COMPLETE DOCUMENTATION WILL BE AVAILABLE IN EARLY 1989.
 
 
         OPERATING ENVIRONMENT
 
         MINIMUM HARDWARE
         . IBM PC/XT OR OTHER 100% IBM - COMPATIBLE PCS
         . 640K MEMORY
         . 10 MB HARD DISK
         . 5 1/4" 360K FLOPPY DISK
         . FOR NETWORK ACCESS
              - INTERNAL MODEM OR
              - HARD WIRE
 
         SOFTWARE REQUIREMENT
         . MS-DOS 2.0 OR SUBSEQUENT RELASE
 
 
 
 
 
         FOR SECURITY REASONS SOME RUN TIME LIMITATIONS HAVE BEEN BUILT
         INTO PC-NTRACK.  THE GENERAL TYPE OF LIMITATIONS ARE LISTED BELOW.  
         FOR SPECIFIC VALUES FOR THESE LIMITATIONS PLEASE CONTACT THE MANAGER 
         OF NETWORK ANALYSIS.
 
         . THE NUMBER OF ITEMS (NODES AND LINKS) FOR WHICH YOU CAN COLLECT 
           STATISTICS
  
         . THE NUMBER OF SNAPS PER RUN OF THE PROGRAM
 
         . THE MINIMUM TIME IN MINUTES BETWEEN SNAPS (PER ITEM)
 
 
 
 
 
 
 
 
 
 
 
         *************************************************************
         *                                                           *
         *   WARNING:  THE SURGEON GENERAL HAS DETERMINED THAT THE   *
         *             OVER USE OF THIS PROGRAM MAY BE DETRIMENTAL   *
         *             TO THE HEALTH OF THE NETWORK.  PLEASE USE     *
         *             THIS PROGRAM WITH EXTREME CAUTION AND DO NOT  *
         *             DISTRIBUTE COPIES TO OTHERS.                  *
         *                                                           *
         *************************************************************
         *************************************************************                           INSTALLATION INSTRUCTIONS
 
 
    TO ACQUIRE A COPY OF PC-NTRACK YOU WILL NEED TO HAVE A VALID USERNAME ON 
    SYSTEM 43.  ONCE YOU HAVE LOGGED INTO 43 ATTACH TO USERNAME NTRACK IN THE 
    READONLY MODE.  TO OBTAIN THE READONLY PASSWORD YOU WILL NEED TO CONTACT 
    THE MANAGER OF NETWORK ANLAYSIS.  ALSO, YOU WILL NEED TO GET THE ACTUAL 
    NAME OF THE EXECUTABLE FILE CONTAINING THE PCNTRACK PROGRAM.  THIS FILE 
    NAME MAY CHANGE FROM TIME TO TIME.
 
    BESIDES THE FILE CONTAINING THE PROGRAM, THERE ARE SEVERAL OTHER FILES 
    WHICH YOU MUST HAVE IN ORDER TO RUN PC-NTRACK.  THESE FILES CONTAIN THE 
    DATA BASE DEFINITION AND WILL CONTAIN THE INFORMATION COLLECTED BY PC-
    NTRACK.
 
    YOU WILL NEED TO MOVE THE FOLLOWING FILES FROM 43 TO YOUR PC.  IF YOU ARE 
    USING TYMCOMM AS YOUR TELECOMMUNICATIONS SOFTWARE YOU MAY TRANSER THE 
    FILES USING THE FOLLOWING COMMANDS.
 
    COPYPC PCNTRACK EXE A1 C:NTRACK.EXE (I
         REMEMBER TO USE THE NAME OF THE EXE FILE THAT YOU GOT FROM THE 
         MANAGER OF NETWORK ANALYSIS.  IT MOST PROBABLY WILL NOT BE PCNTRACK.
         WHEN YOU ATTACH TO NTRACK IT WILL BE ASSIGNED A DIFFERENT CYLINDER 
         NUMBER.  USE THIS CYLINDER NUMBER INSTEAD OF A1.  AFTER THE C: YOU 
         CAN INCLUDE PATH INFORMATION IF YOU WANT.  THE (I INDICATES THAT THIS 
         FILE IS A BINARY FILE AND IS TO BE COPIED IN IMAGE MODE.
 
    COPYPC NTRACK DD1 A1 C:NTRACK.DD1 (I
 
    COPYPC NTRACK DD2 A1 C:NTRACK.DD2 (I
 
    COPYPC NTRACK DD3 A1 C:NTRACK.DD3 (I
 
    COPYPC NTRACK DD4 A1 C:NTRACK.DD4 (I
 
    COPYPC NTRACK DD5 A1 C:NTRACK.DD5 (I
 
    COPYPC NTRACK DK1 A1 C:NTRACK.DK1 (I
 
    COPYPC NTRACK DK2 A1 C:NTRACK.DK2 (I
 
    COPYPC NTRACK DBD A1 C:NTRACK.DBD
         THIS IS A SYMBOLIC FILE AND DOES NOT NEED TO BE TRANSFERED IN IMAGE 
         MODE.
 
    COPYPC NTRACK QIF A1 C:NTRACK.QIF
 
    COPYPC NTRACK H A1 C:NTRACK.H
 
    COPYPC NTRACK NO A1 C:NTRACK
         THIS FILE SHOULD HAVE NO EXTENSION WHEN COPIED TO YOUR PC.  HOWEVER, 
         THE 370 DOES NOT ALLOW A FILE TO HAVE NO EXTENSION SO WE HAVE GIVEN 
         THE FILE AN EXTENSION OF "NO" TO REMIND YOU TO LEAVE THE EXTENSION 
         OFF WHEN IT IS TRANSFERED TO THE PC.
 
    IT IS RECOMMENDED THAT BEFORE YOU USE THE PROGRAM FOR THE FIRST TIME TO 
    BACKUP ALL OF THESE FILES ON A FLOPPY DISK.  SOMETIMES IT IS NECESSARY TO 
    REINITIALIZE YOU DATA BASE FILES AND YOU CAN DO THIS BY COPYING THE FILES 
    FROM YOUR FLOPPY DISK OVER THOSE ON YOUR HARD DISK.
 
    BEFORE RUNNING THE PROGRAM FOR THE FIRST TIME YOU MUST CHECK YOUR 
    CONFIG.SYS FILE FOR THE FOLLOWING...
 
    . MAKE SURE THAT YOU DO NOT HAVE DEVICE = ANSI.SYS IN THE FILE.  PCNTRACK 
      WILL NOT RUN PROPERLY WITH THIS STATEMENT IN YOUR CONFIG.SYS FILE.
 
    . YOU MUST HAVE FILES = 20 IN YOUR CONFIG.SYS FILE
 
 
    ONE MORE THING, AFTER RUNNING PCNTRACK YOU MAY FIND SOME STRANGE FILES IN 
    YOUR DIRECTORY.  THESE FILES ARE RECOGNIZABLE BECAUSE THEY HAVE NAMES WITH 
    THE FORMAT KF?????? AND DF?????? WHERE ?????? ARE ALL NUMERALS.  YOU MAY 
    SAFELY JUST DELETE THESE FILES WHENEVER THEY APPEAR.  THEY ARE TEMP FILES 
    WHICH ARE NOT BEING PROPERLY DISPOSED OF.
 
 
 
 
 
                               RUNNING PCNTRACK
 
    TO RUN PCNTRACK JUST TYPE PCNTRACK ( OR WHATEVER NAME YOU HAVE GIVEN THE 
    FILE CONTAINING THE EXECUTABLE CODE -- THE .EXE FILE ).  THE PROGRAM WILL 
    STARTUP AND YOU WILL SEE THE MAIN MENU OPTIONS ACROSS THE TOP OF YOUR 
    SCREEN.  THE OPTIONS ARE DESCRIBED ON THE SCREEN AS YOU MOVE THE CURSOR 
    FROM OPTION TO OPTION.  THE STANDARD SEQUENCE TO USE THE OPTIONS IS LISTED 
    BELOW.
 
         MAKE - CREATE THE LIST OF NODES OR LINKS FOR WHICH STATISTICS ARE TO 
                BE COLLECTED.
 
         COLLECT - COLLECT THE XRAY STATISTICS
 
         PROCESS - PROCESS THE RAW DATA OBTAINED BY THE COLLECT COMMAND AND 
                   PLACE IT INTO THE NTRACK DATA BASES.
 
         REPORT - GENERATE THE NTRACK REPORTS.
         REPORT - GENERATE THE NTRACK REPORTS.                          NOTES ON MAIN MENU OPTIONS
 
 
                                     MAKE
 
    THE COLLECTION PROCESS WORKS FROM A LIST.  THIS LIST CAN CONTAIN NODES, 
    LINKS OR BOTH.  YOU ARE GIVEN THE OPTION OF ENTERING INFORMATION FOR THE 
    LIST FROM WITHIN THE PCNTRACK PROGRAM OR YOU CAN CREATE AN INPUT FILE 
    USING YOUR OWN WORD PROCESSOR.  IN WITHER CASE YOU WILL NEED THE FOLLOWING 
    INFORMATION.
 
         FOR EACH NODE YOU WILL NEED THE NODE NUMBER AN KERNEL HOST NUMBER.
 
         LINKS ARE DEFINED BY A PAIR OF NODES, ONE ON EITHER END OF THE LINK.  
         FOR EACH LINK IN THE LIST YOU WILL NEED THE NODE NUMBERS FOR EACH 
         NODE THAT DEFINES THE LINK AND THE CORRESPONDING KERNEL HOST NUMBERS.
 
    IF YOU DECIDE TO INPUT THE LIST INFORMATION THROUGH THE PROGRAM YOU WILL 
    BE PROMPTED FOR THE INFORMATION AT THE APPROPRIATE TIME.
 
    IF YOU DECIDE TO CREATE THE INPUT FILES OUTSIDE OF THE PCNTRACK PROGRAM, 
    YOU SHOULD DO SO BEFORE YOU RUN THE PROGRAM.  THEN WHEN YOU ISSUE THE MAKE 
    OPTION YOU WILL BE PROMPTED FOR INPUT FILE NAMES AND THE PROGRAM WILL READ 
    THE INFORMATION FROM THE FILES.  USE THE FOLLOWING FORMATS TO CREATE THE 
    INPUT FILES.
 
         FOR NODE INFORMATION -
 
              PLACE THE INFORMATION FOR EACH NODE ON A SEPARATE LINE.  THE 
              NODE NUMBER SHOULD COME FIRST, THEN A SPACE FOLLOWED BY THE 
              KERNEL HOST NUMBER.  EXAMPLE.
 
                   10510 563
                   4010 4032
 
         FOR LINK INFORMATION -
 
              PLACE THE INFORMATION FOR EACH LINK ON A SEPARATE LINE.  ONE 
              NODE NUMBER SHOULD COME FIRST, A SPACE, THE CORRESPONDING KERNEL 
              HOST NUMBER, A SPACE, THE OTHER NODE, THE OTHER NODE KERNEL HOST 
              NUMBER.  EXAMPLE.
 
                   10510 563 4010 4032
                   2021 21 2022 22
 
 
 
 
                                    COLLECT
 
 
         YOU WILL BE PROMPTED FOR ALL OF THE REQUIRED INFORMATION TO MAKE A 
         CONNECTION TO TYMNET AND TO XRAY.  YOU MAY USE EITHER AN HAYES 
         COMPATIBLE MODEM OR A HARDWIRE LINE.  THE PROGRAM ISSUES THE 
         APPROPRIATE XRAY NS, KS OR ND COMMANDS AND PLACES THE OUTPUT INTO DISK 
         FILES WITH THE EXTENSIONS OF .??R WHERE ?? IS NS, KS OR ND.
 
 
 
                                     PROCESS
 
         AFTER THE XRAY INFORMATION HAS BEEN COLLECTED, IT NEEDS TO BE 
         PROCESSED.  THE PROCESS COMMAND READS THE DATA FROM THE .??R FILES 
         AND PLACES IT EITHER INTO A FIXED FORMAT FLAT FILE ON DISK OR INTO 
         THE NTRACK DATA BASES, OR IT CAN DO BOTH.  YOU CAN MAKE THAT 
         DECISION.  HOWEVER TO BE ABLE TO USE THE REPORT OPTION YOU MUST PLACE 
         THE PROCESSED DATA INTO THE NTRACK DATA BASE.
 
 
 
 
                                    REPORT
 
         THERE ARE THREE LEVELS OF REPORTS.  THE OVERALL SUMMARY REPORT GIVES 
         YOU A SUMMARY OF ALL LINKS AND NODES THAT ARE IN THE COLLECTION LIST 
         OR QUEUE.  THE NEXT LEVEL OF REPORTS GIVES A ONE LINE SUMMARY OF EACH 
         NODE OR LINK.  THIS LEVEL OF REPORTS ARE CALLED THE NODE SUMMARY AND 
         THE LINK SUMMARY.  THE LAST LEVEL OF REPORTS ARE THE DETAILED 
         REPORTS.  THESE REPORTS GIVE A LARGE QUANITY OF INFORMATION ON EACH 
         NODE OR LINK.  WHEN YOU GENERATE THESE REPORTS YOU WILL SEE A 
         SUBMENU.  THE SUBMENU ALLOWS YOU TO SELECT WHICH NODES OR LINKS THAT 
         YOU WANT DETAILED REPORTS FOR.  SOME OF THESE OPTIONS WILL WORK ONLY 
         IF YOU HAVE PROFILE INFORMATION.  THE PROFILE INFORMATION IS ENTERED 
         INTO THE PCNTRACK DATA BASE THROUGH THE IN-PROFILE COMMAND.  THIS 
         COMMAND WILL NOT BE DISCUSSED HERE, BUT WILL BE EXPLAINED IN DETAIL 
         IN THE COMPLETE DOCUMENTATION RELEASED IN 1989.
 
         THE BEST WAY TO FIND OUT ABOUT THESE REPORTS IS TO GENERATE A COPY OF 
         EACH.  BUT REMEMBER YOU MUST FIRST CREATE A QUEUE BY USING THE MAKE 
         COMMAND, THE COLLECT THE DATA USING THE COLLECT COMMAND, AND FINALY 
         PROCESS THE DATA AND PUT IT INTO THE NTRACK DATA BASE USING THE
         PROCESS COMMAND.
 
 
 
 
 
                                     EDIT
 
 
         THIS OPTION WILL NOT BE FULLY DISCUSSED HERE.  BUT THERE ARE TWO OF 
         ITS SUBMENU OPTIONS WHICH YOU WILL FIND USEFUL.  AFTER YOU SELECT THE 
         EDIT MAIN MENU OPTION, A SUBMENU WILL APPEAR.  NOTICE THE OPTIONS 
         CHANGE AND VIEW.  USE THE VIEW OPTION TO SEE THE FIRST FIFTEEN LINES 
         OF THE LIST OF ITEMS IN THE QUEUE.  LOOK AT THE START DATE, START 
         TIME, END DATE, AND END TIME.  MAKE SURE THAT THEY ARE SET SO THAT 
         THE COLLECT WILL OCURR.   IF, FOR EXAMPLE, THE END TIME IS PAST THE 
         CURRENT TIME AND YOU WANT TO COLLECT DATA, USE THE CHANGE OPTION TO 
         CHANGE THE END TIME TO A FUTURE TIME.  THEN WHEN YOU SELECT THE 
         COLLECT OPTION THE PROGRAM WILL BE ABLE TO COLLECT DATA.
 
 
 
 
    