CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                     C
C                                                                     C
C                              GETDAT.FOR                             C
C                                                                     C
C                                                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE GETDAT
   
      COMMON /NODES/ NUMNOD, NODNUM(1000), NODNAM(1000), NODTYP(1000),
     -               NODLON(1000), NODLAT(1000), NODX(1000), NODY(1000)
        DOUBLE PRECISION NODNAM
      INTEGER NUMNOD, NODNUM, NODTYP
      REAL    NODLON, NODLAT, NODX, NODY
   
      COMMON /LINES/ NUMLIN, LINN1(2000), LINN2(2000), LINTYP(2000),
     -               LINBPS(2000), LINGRP(2000), LINNAM(4,2000)
      INTEGER NUMLIN, LINN1, LINN2, LINTYP, LINGRP, LINNAM
      REAL    LINBPS
   
        COMMON /AREA/ INUM(1000),NTYP(10),NDNU1(2000),NDNU2(2000)
     -,LTYP(10),LSPEE(10),XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        INTEGER INUM,NTYP,NDNU1,NDNU2,LTYP,LSPEE
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        REAL XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA

        COMMON /MILES/YLONG(3000),YLAT(3000)
        REAL YLONG,YLAT


        DOUBLE PRECISION FILNA1,FILNA2,LFILE,NFILE,IDATE,INAM
        INTEGER DBNOD,DBLIN,NNMM(4)
        CALL DBF10
        TYPE 10
10      FORMAT(1X,'ENTER THE NAME OF THE DATA BASE
     - FOR THE NODES :?',$)
        READ (5,20) FILNA1
20      FORMAT(A10)

        TYPE 30
30      FORMAT(1X,'ENTER THE NAME OF THE DATA BASE
     - FOR THE LINES :?',$)
        READ (5,40) FILNA2
40      FORMAT(A10)

        CALL DBERR(-1)
        CALL DBOPEN(FILNA1,FILNA2)
        DBNOD=1
        DBLIN=2
        TYPE 1
1       FORMAT(1X,'ENTER THE DATE YOU WANT TO USE IN THE FILES 
     -YYMMDD.NOD',/,1X,' AND YYMMDD.LIN FOR THE STORAGE OF THE NODES',/,
     -1X,'AND LINES SELECTED :?',$)
        READ (5,2) IDATE
2       FORMAT(A10)
        LFILE=IDATE
        CALL STC('.',LFILE,7)
        CALL STC('L',LFILE,8)
        CALL STC('I',LFILE,9)
        CALL STC('N',LFILE,10)
        NFILE=IDATE
        CALL STC('.',NFILE,7)
        CALL STC('N',NFILE,8)
        CALL STC('O',NFILE,9)
        CALL STC('D',NFILE,10)

C       THE USER ENTER WHICH PART OF THE NETWORK HE WANTS TO PLOT
C       AND WE STORE THE INFORMATION IN THE FILES YYMMDD.NOD OR .LIN

        OPEN(UNIT=21,DEVICE='DSK',FILE=NFILE,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=5000)
        WRITE (21,45)
45      FORMAT(1X,'SUBSET OF NODES')
50      CALL PROMPT

        CALL DBSET(DBNOD)
        CALL DBFIND('ALL')
        CALL DBSORT('X','Y')
        I=1
        NUMNOD=0
100     CALL DBGREC($500)
        CALL DBVAL('NODE',NNUM,'NAME',INAM,'X',XLONG,'Y',XLAT,'NTYP',
     -NTYPE)

C       CHECK IF THIS NODE IS WANTED (FLAG = 1)

        CALL CCKNOD(NNUM,NTYPE,XLONG,XLAT,IFLAG)
        IF (IFLAG.EQ.0) GOTO 100
C       ELSE KEEP THIS RECORD AND STORE IT IN THE FILE YYMMDD.NOD
        WRITE (21,110) NNUM,INAM,XLONG,XLAT,NTYPE
110     FORMAT(1X,I4,1X,A10,1X,F10.5,1X,F10.5,1X,I2)
        NODNAM(I)=INAM
        NODTYP(I)=NTYPE
        NODLON(I)=XLONG
        NODLAT(I)=XLAT
        YLAT(NNUM)=XLAT
        YLONG(NNUM)=XLONG
        NODNUM(I)=NNUM
        I=I+1
        NUMNOD=NUMNOD+1
        GOTO 100

500     CLOSE(UNIT=21)
        WRITE (5,510) NUMNOD
510     FORMAT(/,1X,'THERE ARE ',I4,' NODES REMAINING.',/,
     -1X,'DO YOU THINK IT IS OK?',$)
515     READ (5,520) ITEST
520     FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 50
        IF (ITEST.NE.'Y') GOTO 515
        OPEN(UNIT=22,DEVICE='DSK',FILE=LFILE,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=5000)
        WRITE (22,46)
46      FORMAT(1X,'SUBSET OF LINES')

        CALL DBSET(DBLIN)
        CALL DBFIND('ALL')
        I=1
        NUMLIN=0
600     CALL DBGREC($1000)
        CALL DBVAL('NOD1',NUM1,'NOD2',NUM2,'LTYP',LTYPE,
     -'BAUD',IBDS,'GRPS',IGPS,'NAME',NNMM)

C       CHECK IF THIS LINE IS WANTED (FLAG=1)

        CALL CCKLIN(NODNUM,NUMNOD,NUM1,NUM2,LTYPE,IBDS,IGPS,NNMM,IFLAG)
        IF (IFLAG.EQ.0) GOTO 600
C       ELSE KEEP THIS RECORD AND STORE IT IN THE COMMON
        WRITE (22,605) NUM1,NUM2,LTYPE,IBDS,IGPS,(NNMM(I),I=1,4)
605     FORMAT(1X,I4,1X,I4,I2,1X,A4,1X,I2,1X,4A5)
        LINN1(I)=NUM1
        LINN2(I)=NUM2
        LINTYP(I)=LTYPE
        LINBPS(I)=IBDS
        LINGRP(I)=IGPS
        DO 606 II=1,4
        LINNAM(II,I)=NNMM(II)
606     CONTINUE
        I=I+1
        NUMLIN=NUMLIN+1
        GOTO 600

1000    CLOSE(UNIT=22)
        WRITE (5,1010) NUMLIN
1010    FORMAT(/,1X,'THERE ARE ',I4,' LINES REMAINING.',/,
     -1X,'DO YOU THINK IT IS OK?',$)
1015    READ (5,1020) ITEST
1020    FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 50
        IF (ITEST.NE.'Y') GOTO 1015

        CALL DBCLOS
        CALL DBCLOS
        CALL DBEND
        GOTO 10000

5000    TYPE 5001
5001    FORMAT(1X,'ERROR CAN T OPEN THE RESULT FILES')
10000   RETURN
        END
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
        SUBROUTINE PROMPT
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        COMMON /AREA/ INUM(1000),NTYP(10),NDNU1(2000),NDNU2(2000)
     -,LTYP(10),LSPEE(10),XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        INTEGER INUM,NTYP,NDNU1,NDNU2,LTYP,LSPEE
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        REAL XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA

        DOUBLE PRECISION IFIL1,IFIL2,IFIL3,IFIL4

        ITOTN=0
        ITYT=0
        ITOTL=0
        ITYLT=0
        ISPLT=0

        TYPE 10
10      FORMAT(1X,'DO YOU WANT TO ENTER A LIST OF 
     - NODE NUMBERS ?',$)
15      READ (5,20) ITEST
20      FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 99
        IF (ITEST.NE.'Y') GOTO 15

        IALL=1
        TYPE 30
30      FORMAT(1X,'FROM THE TERMINAL (ENTER 1)
     - OR FROM A FILE (ENTER 2) ?',$)
35      READ (5,40) ITEST
40      FORMAT(I1)
        IF (ITEST.EQ.2) GOTO 60
        IF (ITEST.NE.1) GOTO 35

        
        TYPE 41
41      FORMAT(1X,'ENTER NODE NUMBERS ONE AFTER THE OTHER
     - AND ENTER A CR TO END THE LIST')
        I=1
        ITOTN=0
45      TYPE 46
46      FORMAT(1X,'NODE NUMBER = ',$)
        READ (5,47) INUM(I)
47      FORMAT(I)
        IF (INUM(I).EQ.0) GOTO 50
        IF (INUM(I).LT.0.OR.INUM(I).GT.3000) GOTO 45
        I=I+1
        ITOTN=ITOTN+1
        GOTO 45
50      TYPE 51
51      FORMAT(1X,'ENTER A FILENAME IF YOU WANT TO SAVE 
     -THIS LIST ,ELSE CR :?',$)
        READ (5,52) IFIL1
52      FORMAT(A10)
        IF (IFIL1.EQ.' ') GOTO 100
        OPEN (UNIT=21,DEVICE='DSK',FILE=IFIL1,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=50)
        DO 54 I=1,ITOTN
        WRITE (21,53) INUM(I)
53      FORMAT (1X,I4)
54      CONTINUE
        CLOSE (UNIT=21)
        GOTO 100

60      TYPE 61
61      FORMAT(1X,'ENTER DATA FILENAME ?',$)
        READ (5,62) IFIL2
62      FORMAT(A10)
        OPEN(UNIT=21,DEVICE='DSK',FILE=IFIL2,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=60)
        I=1
65      READ (21,66,END=70) INUM(I)
66      FORMAT(1X,I4)
        I=I+1
        GOTO 65
70      ITOTN=I-1
        CLOSE (UNIT=21)


        GOTO 100
99     IALL=0
100     TYPE 101
101     FORMAT(1X,'DO YOU WANT TO ENTER A LIST OF NODE TYPES?',$)
        READ (5,202) ITEST
        IF (ITEST.EQ.'N') GOTO 199
        IF (ITEST.NE.'Y') GOTO 100

        IALLTN=1
        TYPE 102
102     FORMAT(1X,'ENTER NODE TYPE OR A 999 
     - TO END THE LIST')
        I=1
        ITYT=0
103     TYPE 104
104     FORMAT(1X,'NODE TYPE = ',$)
        READ (5,105) NTYP(I)
105     FORMAT(I)
        IF (NTYP(I).EQ.999) GOTO 200
        I=I+1
        ITYT=ITYT+1
        GOTO103


199     IALLTN=0
200     TYPE 201
201     FORMAT(1X,'DO YOU WANT A REGIONNAL MAP ?',$)
        READ (5,202) ITEST
202     FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 299
        IF (ITEST.NE.'Y') GOTO 200

        IREG=1
        TYPE 203
203     FORMAT(1X,'ENTER MINIMUM AND MAXIMUM LONGITUDE : ',$)
        READ (5,204) XLOMIN,XLOMAX
204     FORMAT(2G)
        TYPE 205
205     FORMAT(1X,'ENTER MINIMUM AND MAXIMUM LATITUDE : ',$)
        READ (5,206) YLAMIN,YLAMAX
206     FORMAT(2G)


        GOTO 300
299     IREG=0
300     TYPE 301
301     FORMAT(1X,'DO YOU WANT TO ENTER A LIST OF LINES ?',$)
        READ (5,302) ITEST
302     FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 399
        IF (ITEST.NE.'Y') GOTO 300

        IALLL=1
        TYPE 303
303     FORMAT(1X,'FROM THE TERMINAL (ENTER 1)
     - OR FROM A FILE (ENTER 2) ?',$)
        
304     READ (5,305) ITEST
305     FORMAT(I1)
        IF (ITEST.EQ.2) GOTO 350
        IF (ITEST.NE.1) GOTO 304

        TYPE 310
310     FORMAT(1X,'ENTER BOTH NODE NUMBER OR CR TO END THE LIST:')
        I=1
        ITOTL=0
311     TYPE 312
312     FORMAT(1X,'NODE1 , NODE2 = ',$)
        READ (5,313) NDNU1(I),NDNU2(I)
313     FORMAT(I,1X,I)
        IF (NDNU1(I).EQ.0) GOTO 320
        I=I+1
        ITOTL=ITOTL+1
        GOTO 311

320     TYPE 321
321     FORMAT(1X,'ENTER A FILENAME IF YOU WANT TO SAVE THIS
     - LIST,ELSE CR :?',$)
        READ (5,322) IFIL3
322     FORMAT(A10)
        IF (IFIL3.EQ.' ') GOTO 400
        OPEN (UNIT=21,DEVICE='DSK',FILE=IFIL3,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=320)
        DO 323 I=1,ITOTL
        WRITE (21,324) NDNU1(I),NDNU2(I)
324     FORMAT(1X,I4,1X,I4)
323     CONTINUE
        CLOSE (UNIT=21)
        GOTO 400

350     TYPE 351
351     FORMAT(1X,'ENTER DATA FILENAME ?',$)
        READ (5,352) IFIL4
352     FORMAT(A10)
        OPEN(UNIT=21,DEVICE='DSK',FILE=IFIL4,ACCESS='SEQINOUT',
     -MODE='ASCII',ERR=350)
        I=1
353     READ (21,354,END=370) NDNU1(I),NDNU2(I)
354     FORMAT(1X,I4,1X,I4)
        I=I+1
        GOTO 353

370     ITOTL=I-1
        CLOSE(UNIT=21)

        GOTO 400
399     IALLL=0
400     TYPE 401
401     FORMAT(1X,'DO YOU WANT TO ENTER A LIST OF LINE TYPES?',$)
        READ (5,202) ITEST
        IF (ITEST.EQ.'N') GOTO 499
        IF (ITEST.NE.'Y') GOTO 400

        IALLTL=1
        TYPE 402
402     FORMAT(1X,'ENTER LINE TYPE OR A 999 TO END THE LIST.')
        I=1
        ITYLT=0
403     TYPE 404
404     FORMAT(1X,'LINE TYPE = ',$)
        READ (5,405) LTYP(I)
405     FORMAT(I)
        IF (LTYP(I).EQ.999) GOTO 500
        I=I+1
        ITYLT=ITYLT+1
        GOTO 403

499     IALLTL=0
500     TYPE 501
501     FORMAT(1X,'DO YOU WANT TO ENTER A LIST OF SPEED?',$)
        READ (5,202) ITEST
        IF (ITEST.EQ.'N') GOTO 599
        IF (ITEST.NE.'Y') GOTO 500

        ISPEED=1
        TYPE 502
502     FORMAT(1X,'ENTER LINE SPEED OR ' ' TO END THE LIST.')
        I=1
        ISPLT=0
503     TYPE 504
504     FORMAT(1X,'LINE SPEED = ',$)
        READ (5,505) LSPEE(I)
505     FORMAT(A5)
        IF (LSPEE(I).EQ.' ') GOTO 600
        I=I+1
        ISPLT=ISPLT+1
        GOTO 503

599     ISPEED=0
600     TYPE 601
601     FORMAT(1X,'DO YOU WANT TO RESTRICT THE MILEAGE ?',$)
        READ (5,602) ITEST
602     FORMAT(A1)
        IF (ITEST.EQ.'N') GOTO 699
        IF (ITEST.NE.'Y') GOTO 600

        IMILE=1
        TYPE 603
603     FORMAT(1X,'ENTER MINIMUM AND MAXIMUM : ',$)
        READ (5,604) XMILMI,XMILMA
604     FORMAT(2G)

        GOTO 700
699     IMILE=0
700     RETURN
        END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
        SUBROUTINE CCKNOD(NUMB,TYPE,XLON,XLA,FLAG)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      COMMON /NODES/ NUMNOD, NODNUM(1000), NODNAM(1000), NODTYP(1000),
     -               NODLON(1000), NODLAT(1000), NODX(1000), NODY(1000)
        DOUBLE PRECISION NODNAM
      INTEGER NUMNOD, NODNUM, NODTYP
      REAL    NODLON, NODLAT, NODX, NODY
   
      COMMON /LINES/ NUMLIN, LINN1(2000), LINN2(2000), LINTYP(2000),
     -               LINBPS(2000), LINGRP(2000), LINNAM(4,2000)
      INTEGER NUMLIN, LINN1, LINN2, LINTYP, LINGRP, LINNAM
      REAL    LINBPS

        COMMON /AREA/ INUM(1000),NTYP(10),NDNU1(2000),NDNU2(2000)
     -,LTYP(10),LSPEE(10),XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        INTEGER INUM,NTYP,NDNU1,NDNU2,LTYP,LSPEE
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        REAL XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA

        INTEGER NUMB,TYPE,FLAG
        REAL XLON,XLA

        FLAG=1

        IF (IALL.EQ.0) GOTO 30
        DO 10 K=1,ITOTN
        IF (INUM(K).EQ.NUMB) GOTO 30
10      CONTINUE
        FLAG=0
        GOTO 1000

30      IF (IALLTN.EQ.0) GOTO 60
        DO 40 I=1,ITYT
        IF (NTYP(I).EQ.TYPE) GOTO 60
40      CONTINUE
        FLAG=0
        GOTO 1000
60      IF (IREG.EQ.0) GOTO 1000
        IF (XLON.LT.XLOMIN.OR.XLON.GT.XLOMAX) FLAG=0
        IF (XLA.LT.YLAMIN.OR.XLA.GT.YLAMAX) FLAG=0

1000    RETURN
        END


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
        SUBROUTINE CCKLIN(NUMN,NODN,N1,N2,LTYPB,IBAUD,IGROUP,NAME,FLAG)
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      COMMON /NODES/ NUMNOD, NODNUM(1000), NODNAM(1000), NODTYP(1000),
     -               NODLON(1000), NODLAT(1000), NODX(1000), NODY(1000)
        DOUBLE PRECISION NODNAM
      INTEGER NUMNOD, NODNUM, NODTYP
      REAL    NODLON, NODLAT, NODX, NODY
   
      COMMON /LINES/ NUMLIN, LINN1(2000), LINN2(2000), LINTYP(2000),
     -               LINBPS(2000), LINGRP(2000), LINNAM(4,2000)
      INTEGER NUMLIN, LINN1, LINN2, LINTYP, LINGRP, LINNAM
      REAL    LINBPS

        COMMON /AREA/ INUM(1000),NTYP(10),NDNU1(2000),NDNU2(2000)
     -,LTYP(10),LSPEE(10),XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        INTEGER INUM,NTYP,NDNU1,NDNU2,LTYP,LSPEE
     -,ITOTN,ITYT,ITOTL,ITYLT,ISPLT,IALL
     -,IALLTN,IREG,IALLL,IALLTL,ISPEED,IMILE
        REAL XLOMIN,XLOMAX,YLAMIN,YLAMAX,XMILMI,XMILMA

        COMMON /MILES/YLONG(3000),YLAT(3000)
        REAL YLONG,YLAT

        INTEGER FLAG,NUMN(1000)

        FLAG=1

        ITEST=0

        DO 10 K=1,NODN
        IF (N1.EQ.NUMN(K)) GOTO 20
10      CONTINUE
        ITEST=ITEST+1

20      DO 30 K=1,NODN
        IF(N2.EQ.NUMN(K)) GOTO 50
30      CONTINUE
        ITEST=ITEST+1
        IF (ITEST.EQ.2) FLAG=0
        IF (ITEST.EQ.2) GOTO 1000


50      IF (IALLL.EQ.0) GOTO 60
        DO 55 K=1,ITOTL
        IF (N1.EQ.NDNU1(K).AND.N2.EQ.NDNU2(K)) GOTO 60
55      CONTINUE
        FLAG=0
        GOTO 1000

60      IF (IALLTL.EQ.0) GOTO 70
        DO 65 K=1,ITYLT
        IF (LTYPB.EQ.LTYP(K)) GOTO 70
65      CONTINUE
        FLAG=0
        GOTO 1000

70      IF (ISPEED.EQ.0) GOTO 80
        DO 75 K=1,ISPLT
        IF (IBAUD.EQ.LSPEE(K)) GOTO 80
75      CONTINUE
        FLAG=0
        GOTO 1000

80      IF (IMILE.EQ.0) GOTO 1000
        CALL DIST1(YLAT(N1),YLONG(N1),YLAT(N2),YLONG(N2),D1)
        IF (D1.GE.XMILMI.AND.D1.LE.XMILMA) GOTO 1000
        FLAG=0

1000    RETURN
        END
   