CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C                                                                     C
C               POSPLT                                          C
C                                                               C
C       THIS PROGRAMM SELECT ASUBSET OF NODES AND LINES         C
C       FROM PLOT.NOD AND PLOT.LIN AND/OR POSITIONNE            C
C       THESE NODES FOR THE PLOTTING                            C
C                                                                     C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      COMMON /NODES/ NUMNOD, NODNUM(1000), NODNAM(1000), NODTYP(1000),
     -               NODLON(1000), NODLAT(1000), NODX(1000), NODY(1000)
        DOUBLE PRECISION NODNAM
      INTEGER NUMNOD, NODNUM, NODTYP
      REAL    NODLON, NODLAT, NODX, NODY
   
      COMMON /LINES/ NUMLIN, LINN1(2000), LINN2(2000), LINTYP(2000),
     -               LINBPS(2000), LINGRP(2000), LINNAM(4,2000)
      INTEGER NUMLIN, LINN1, LINN2, LINTYP, LINGRP, LINNAM
      REAL    LINBPS
   
      INTEGER PLTMAT(21,59)
      REAL    MINLON, MAXLON, MINLAT, MAXLAT
        DOUBLE PRECISION IFIL1,IFIL2,FILNAM


1       TYPE 2
2       FORMAT(1X,'DO YOU WANT TO SELECT NODES AND LINES (1)',/,
     -1X,'OR YOU HAVE ALREADY DATA FILES OF THE SUBNETWORK (2) :?',$)
        READ (5,3) ITEST
3       FORMAT(I1)

        IF (ITEST.EQ.1) GOTO 8
        IF (ITEST.NE.2) GOTO 1

        TYPE 4
4       FORMAT(1X,'ENTER FILENAMES :?',$)
        READ (5,5) IFIL1,IFIL2
5       FORMAT(A10,1X,A10)

        OPEN(UNIT=21,DEVICE='DSK',FILE=IFIL1,
     -ACCESS='SEQINOUT',MODE='ASCII',ERR=1)
        OPEN(UNIT=22,DEVICE='DSK',FILE=IFIL2,
     -ACCESS='SEQINOUT',MODE='ASCII',ERR=1)
        READ (21,6) ITEST
        READ (22,6) ITEST
6       FORMAT(A1)

        DO 7 K=1,1000
        READ (21,33,ERR=38,END=34) NODNUM(K),NODNAM(K),NODLON(K),
     -NODLAT(K),NODTYP(K)
33      FORMAT(1X,I4,1X,A10,1X,F10.5,1X,F10.5,1X,I2)
        NUMNOD=NUMNOD+1
7       CONTINUE

34      DO 36 K=1,2000
        READ (22,35,ERR=38,END=37) LINN1(K),LINN2(K),LINTYP(K),
     -LINBPS(K),LINGRP(K),(LINNAM(I,K),I=1,4)
35      FORMAT(1X,I4,1X,I4,I2,1X,A4,1X,I2,1X,4A5)
        NUMLIN=NUMLIN+1
36       CONTINUE

37      CLOSE(UNIT=21)
        CLOSE(UNIT=22)
        GOTO 9
        
38      TYPE 39
39      FORMAT(1X,'ERROR READING TOPOLOGY FILES')
        GOTO 9
   
      
8       CALL GETDAT
   
9       TYPE 31
31      FORMAT(1X,'DO YOU WANT TO POSITIONNE THE NODES?',$)
        READ (5,32) ITEST
32      FORMAT(A1)
        IF (ITEST.EQ.'Y') GOTO 322
        IF (ITEST.NE.'N') GOTO 9
        GOTO 60

322       MINLON=NODLON(1)
        MAXLON=NODLON(1)
        MINLAT=NODLAT(1)
        MAXLAT=NODLAT(1)

        DO 10 N=1,NUMNOD
        IF (NODLON(N).LT.MINLON) MINLON=NODLON(N)
        IF (NODLON(N).GT.MAXLON) MAXLON=NODLON(N)
        IF (NODLAT(N).LT.MINLAT) MINLAT=NODLAT(N)
        IF (NODLAT(N).GT.MAXLAT) MAXLAT=NODLAT(N)
10      CONTINUE
   
20      TYPE 21
21      FORMAT(1X,'HOW MANY ITERATIONS DO YOU WANT?',$)
        READ (5,22) ITEST
22      FORMAT(I3)

        ITEST=ITEST+1
        DO 25 K=1,1000
        IF (K.GE.ITEST) GOTO 26
        CALL MAPXY(PLTMAT,0)
25      CONTINUE

26      CALL PLT1(PLTMAT)

27      TYPE 28
28      FORMAT(1X,'MORE ITERATIONS ? (Y OR N)',$)
        READ (5,29) ITEST
29      FORMAT(A1)
        IF (ITEST.EQ.'Y') GOTO 20
        IF (ITEST.NE.'N') GOTO 27
        CALL MAPXY(PLTMAT,1)
        CALL PLT1(PLTMAT)

   
C     DO 40  IY=1,20
C        DO 30  IX=1,58
C           IF (PLTMAT(IY,IX).EQ.0) GOTO 30
C           X = IX + 0.5
C           Y = IY + 0.5
C           WRITE(TTY,1020) PLTMAT(IY,IX),X,Y
C  30       CONTINUE
C  40    CONTINUE
   
      CALL DONEPL
   
        XFACT=(MAXLON-MINLON)/58.
        YFACT=(MAXLAT-MINLAT)/20.
        DO 50 K=1,NUMNOD
        NODLON(K)=MINLON+NODX(K)*XFACT
        NODLAT(K)=MINLAT+NODY(K)*YFACT
50      CONTINUE

60      TYPE 70
70      FORMAT(1X,'PLOTTING THE NETWORK :(Y OR N)?',$)
        READ (5,80) ITEST
80      FORMAT(A1)
        IF (ITEST.EQ.'Y') GOTO 100
        IF (ITEST.NE.'N') GOTO 60
        GOTO 142

100     CALL PLONET

142      TYPE 143
143      FORMAT(/,1X,'DO YOU WANT TO SAVE THE NEW TOPOLOGY',/,
     -1X,'IF YOU HAVE NOT ALREADY SAVED IT ?',$)
        READ(5,144,ERR=142) IRESP
144      FORMAT(A1)
        IF (IRESP.EQ.'Y') GOTO 145
        IF (IRESP.EQ.'N') GOTO 500
        GOTO142

145      TYPE 146
146      FORMAT (/,1X,'ENTER FILENAME')
        READ (5,147,ERR=145) FILNAM
147      FORMAT(A10)

        OPEN(UNIT=21,DEVICE='DSK',FILE=FILNAM,
     -ACCESS='SEQINOUT',MODE='ASCII',ERR=145)
        WRITE(21,333)
333     FORMAT(1X,'SUBSET OF NODES')
        DO 148 I=1,NUMNOD
        WRITE(21,149,ERR=148) NODNUM(I),NODNAM(I),NODLON(I),NODLAT(I)
     -,NODTYP(I)
149      FORMAT(1X,I4,1X,A10,1X,F10.5,1X,F10.5,1X,I2)
148      CONTINUE
500     STOP
   
C                       *** FORMATS ***
 1000 FORMAT(' MINLON = ',F7.2,5X,'MAXLON = ',F7.2/,
     -       ' MINLAT = ',F7.2,5X,'MAXLAT = ',F7.2//)
 1010 FORMAT(' NODE = ',I5,3X,'NODLON = ',F7.2,3X,'NODLAT = ',
     -       F7.2/,
     -       '        ',8X,'NODX   = ',F7.2,3X,'NODY   = ',
     -       F7.2//)
 1020 FORMAT(' PLTMAT = ',I5,3X,'X = ',F7.2,3X,'Y = ',F7.2)
  
      END
