
************************************************************************
*                                                                      *
*                         PROGRAM:  PLOOK                              *
*                                                                      *
*       THIS PROGRAM WILL LOG INTO PROBE AND RETRIEVE ALL INFOR-       *
*       MATION ABOUT A PARTICULAR NODE, SUCH AS NODE TYPE, HOSTS       *
*       AND NEIGHBORS. THE DMC FILE TO LOAD THIS PROGRAM IS GIVEN      *
*       IN PLOOK.DMC. ALSO, AN AC LICENSE IS NEEDED EVERY TIME THE     *
*       PROGRAM IS RECOMPILED OR TRANSFERRED TO ANOTHER DIRECTORY.     *
*       FOR ANY QUESTION REGARDING THIS PROGRAM, CONTACT MANHDO AT     *
*       EXTENSION 7182. BASICALLY THE PROGRAM WORKS AS FOLLOWS:        *
*       BUILD AN AUX CIRCUIT TO THE ACTIVE SUP, SEND THE 'N' COM-      *
*       MAND AND DUMP THE PROBE OUTPUT TO A TEMPORARY FILE. THEN       *
*       COMMAND-10 PACKAGE IS USED TO INTERPRET THIS OUTPUT IN A       *
*       MEANINGFUL WAY.                                                *
*                                                                      *
************************************************************************

        INTEGER PORT,COLON,RESULT,CHAR,CR,HCOUNT,PROBE(2),USERNA(6),
     X  PASSWD(9),TABLE(1234),HSTATE(16),BLANK
        DIMENSION KILL(5),N(8),ILINE(72),NODNUM(4),NODNAM(2,0/1855),
     X  LFILE(4),NFILE(4),IHOST(16),IBAUD(32),NGRPS(32),NBOR(15),
     X  NEINAM(32,2),LINE(32,4),LNAM(4),NNAME(2),IDATE(2),LSTATE(32),
     X  LSTEMP(32),NNEIGH(32),NEIGH(32),NEITYP(32)
     X  ,NONOD(33),NTYPE(33),INONA(33,2),NLTYP(32)
     X  ,IXDTE(2)
        DOUBLE PRECISION IOFILE,JOFILE,NNNAM
        COMMON /COMPKG/TABLE
        COMMON /PRBE/PORT

        DATA PROBE/'PROBE:*;  '/
        DATA COLON/58/,LF/10/,CR/13/
        DATA KILL/4,69,88,73,13/
        DATA USERNA/5,68,79,73,84,13/
        DATA PASSWD/8,84,82,79,85,66,76,69,13/
        DATA N(2)/78/,N(3)/32/
        DATA (NBOR(I),I=1,10)/14,78,69,73,71,72,66,79,82,32/
        DATA NBOR(15)/13/
        DATA BLANK/'     '/
        DATA NULL/"001004020100/

        CALL DBF10

        TABLE(3)=20
        TABLE(5)=72
        TABLE(22)=0
        ASSIGN 885 TO TABLE(6)
C
C  BUILD TEMPORARY FILENAME
C
        IOFILE='A01MI.TMP '
        JOFILE='B01MI.TMP '
C
C  INITIALISE THE NODE NAMES TABLE
C
        DO 80 I=0,1855
        NODNAM(1,I)=0
        NODNAM(2,I)=0
80      CONTINUE
C
C  BUILD AUX CIRCUIT TO PROBE
C
        CALL FBCIR(PROBE,PORT,IER)
        IF (IER.EQ.0) GO TO 110
        TYPE 100,IER
100     FORMAT(' UNABLE TO BUILD CIRCUIT, RESPONSE: ',O12)
        STOP
C
C  SEND PROBE LOGIN AFTER EATING A COLON
C
110     CALL SCAN(COLON,RESULT)
        IF (RESULT.EQ.1) GO TO 130
        TYPE 120
120     FORMAT(' BAD PROBE RESPONSE')
        STOP
C
C  SEND USERNAME AND PASSWORD
C
130     CALL SEND(USERNA)
        CALL SCAN(COLON,RESULT)
        IF (RESULT.NE.1) GO TO 110
        CALL SEND(PASSWD)
        CALL SCAN(COLON,RESULT)
        IF (RESULT.NE.1) GO TO 110
C
C  INTO PROBE, TELL USER
C
        TYPE 135
135     FORMAT(/1X,'LOGGED INTO PROBE')
        CALL ONINT($2000)
C
C  PROMPT FOR FILENAMES AND NODE NUMBER
C
        ID=5
        TYPE 136
136     FORMAT(' FILENAME FOR ''PLOT'' DATA BASES : ',$)
        READ(5,147) LFILE
147     FORMAT(4A5)
        DO 148 I=1,4
        NFILE(I)=LFILE(I)
148     CONTINUE
        
C
C  FIND FIRST BLANK IN 'LFILE'
        DO 137 I=1,20
        IJ=I
        CALL RTC(ICHAR,LFILE,IJ)
        IF (ICHAR.EQ.' ') GO TO 139
137     CONTINUE
C
C  ERROR, FILENAME EXCEEDS 20 CHARACTERS
        TYPE 138,LFILE
138     FORMAT(' FILENAME ',5A5,' EXCEEDS 20 CHARACTERS')
        GO TO 2000
C
C  ADD EXTENSION '.LIN'
139     CALL STC('.',LFILE,I)
        CALL STC('L',LFILE,I+1)
        CALL STC('I',LFILE,I+2)
        CALL STC('N',LFILE,I+3)
C
C       ADD EXTENSION '.NOD'
        CALL STC('.',NFILE,I)
        CALL STC('N',NFILE,I+1)
        CALL STC('O',NFILE,I+2)
        CALL STC('D',NFILE,I+3)
C
C       OPEN DATA BASE 'PLOT.NOD' TO RETRIEVE NODE NAMES
C
        CALL DBOPEN(NFILE)
        CALL DBFIND('ALL')
140     CALL DBGREC($145)
        CALL DBVAL('NODE',I,'NAME',NNNAM)
        IF ((I.LE.0).OR.(I.GT.777.AND.I.LT.1000).OR.(I.GT.1777.AND.
     +  I.LT.2000).OR.(I.GT.2777)) GO TO 140
        CALL CONVRT(I,IDEC)
        I=IDEC
        DO 141 K=1,5
        IJ=K
        CALL RTC(ICHAR,NNNAM,IJ)
        CALL STC(ICHAR,NODNAM(1,I),IJ)
141     CONTINUE
        DO 142 K=6,10
        IJ=K
        CALL RTC(ICHAR,NNNAM,IJ)
        CALL STC(ICHAR,NODNAM(2,I),K-5)
142     CONTINUE
        GO TO 140

145     CALL DBCLOS
151     TYPE 152
152     FORMAT(//1X,'NODE NUMBER ?',$)
        READ(5,154,ERR=151) NODENO
154     FORMAT(O4)
155     FORMAT(I4)
        IF (NODENO.EQ.0) GO TO 2000
C
C  RE-INITIALISE ALL VARIABLES
        NSTATE=0
        NTYP=0
        DO 165 I=1,32
        LSTATE(I)=BLANK
        IBAUD(I)=BLANK
        NGRPS(I)=0
        NEIGH(I)=0
        DO 160 J=1,2
        NEINAM(I,J)=BLANK
160     CONTINUE
        DO 162 J=1,4
        LINE(I,J)=BLANK
162     CONTINUE
165     CONTINUE
        DO 167 I=1,2
        NNAME(I)=BLANK
167     CONTINUE
        DO 169 I=1,16
        IHOST(I)=0
        HSTATE(I)=BLANK
169     CONTINUE
        OPEN(UNIT=21,FILE=IOFILE,ACCESS='SEQOUT',MODE='ASCII')
        IPOS=1
        IF (NODENO.GE."10) GO TO 294
C
C  BUILD HERE THE 'N X' COMMAND
C
        REREAD 292,NODNUM(1)
292     FORMAT(3X,A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        N(1)=4
        N(5)=13
        N(4)=NODNUM(1)
        WRITE(21,293) NODENO
293     FORMAT('NODE ',O1)
        GO TO 320
294     IF (NODENO.GE."100) GO TO 300
C
C  BUILD HERE THE 'N XX' COMMAND
C
        REREAD 295,(NODNUM(I),I=1,2)
295     FORMAT(2X,2A1)
C
C  RIGHT SHIFT 29 BITS TO MAKE IT RIGHT JUSTIFIED
C
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        N(1)=5
        N(6)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        WRITE(21,296) NODENO
296     FORMAT('NODE ',O2)
        GO TO 320
300     IF (NODENO.GE."1000) GO TO 310
C
C  BUILD HERE THE 'N XXX' COMMAND
C
        REREAD 305,(NODNUM(I),I=1,3)
305     FORMAT(1X,3A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        NODNUM(3)=LSH(NODNUM(3),-29)
        N(1)=6
        N(7)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        N(6)=NODNUM(3)
        WRITE(21,306) NODENO
306     FORMAT('NODE ',O3)
        GO TO 320
C
C  BUILD HERE THE 'N XXXX' COMMAND
C
310     REREAD 315,(NODNUM(I),I=1,4)
315     FORMAT(4A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        NODNUM(3)=LSH(NODNUM(3),-29)
        NODNUM(4)=LSH(NODNUM(4),-29)
        N(1)=7
        N(8)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        N(6)=NODNUM(3)
        N(7)=NODNUM(4)
        WRITE(21,316) NODENO
316     FORMAT('NODE ',O4)
        IF (NODENO.LT."2000) GO TO 320
        NBOR(11)=NODNUM(1)
        NBOR(12)=NODNUM(2)
        NBOR(13)=NODNUM(3)
        NBOR(14)=NODNUM(4)
C
C  SEND OUT THE 'N' COMMAND
C
320     CALL SEND(N)
C
C  NOW GET OUTPUT FROM PROBE CHAR BY CHAR
C
330     CALL WAIT(1.0)
335     CALL GTCHAR(PORT,CHAR)
        IF (CHAR.LT.0) GO TO 330
        CHAR=IAND(CHAR,127)
C
C  CHECK IF END OF OUTPUT FROM PROBE
C
        IF (CHAR.EQ.COLON) GO TO 345
        IF (CHAR.EQ.CR) GO TO 340
        IF (CHAR.EQ.LF) GO TO 335
        CHAR=LSH(CHAR,29)
        ILINE(IPOS)=CHAR
        IPOS=IPOS+1
        GO TO 335
340     IPOS=IPOS-1
        WRITE(21,341) (ILINE(I),I=1,IPOS)
341     FORMAT(72A1)
        IPOS=1
        GO TO 335
C
C  FROM NOW ON TRY TO USE COMMAND-10 TO INTERPRET PROBE OUTPUT
C
345     CLOSE(UNIT=21)
        ISTEP=0
        OPEN(UNIT=20,FILE=IOFILE,ACCESS='SEQIN',MODE='ASCII')
        ASSIGN 895 TO TABLE(8)
C
C  GET A LINE OF INPUT
C
350     CALL NEWLIN
C
C  NOW SCAN FOR A PRIMARY COMMAND (LIST # 1)
C
        CALL CMND(-1,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 750
        GO TO (400,450,500,550,600,650,700) NUM
C
C  LINE WITH 'NODE NUMBER'
C
400     IF (ISTEP.NE.0) GO TO 850
        ISTEP=1
        CALL OCTAL(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 850
        IF (INT.NE.NODENO) GO TO 850
        GO TO 350
C
C  LINE WITH 'NO SUCH NODE'
C
450     IF (ISTEP.NE.1) GO TO 855
        CALL CMND(-7,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 855
        ISTEP=0
        GO TO 890
C
C  LINE WITH 'VERSION ETC.'
C
500     IF (ISTEP.NE.1) GO TO 860
        ISTEP=2
C
C  RETRIEVE VERSION NUMBER OF NODE CODE
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 860
        IVERS=INT
        CALL CMND(-2,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 860
C
C  RETRIEVE NOW THE NODE TYPE
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 860
        IF (INT.GT.9) GO TO 860
        NTYP=INT
        GO TO 350
C
C  LINE WITH 'PORTS ETC.'
C
550     IF (ISTEP.NE.2) GO TO 865
C
C  EAT UP INTEGER REPRENSENTING THE NO. OF PORTS USED
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 865
        CALL CMND(-3,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 865
        IF (NODENO.LT."1000) ISTEP=3
        IF (NODENO.LT."2000.AND.NODENO.GE."1000) ISTEP=4
        IF (NODENO.GE."2000) GO TO 865
        GO TO 350
C
C  LINE WITH 'AVAILABLE PASSTHROUGHS'
C
600     IF (ISTEP.NE.2) GO TO 870
        IF (NTYP.NE.9.OR.NODENO.LT."2000) GO TO 870
        ISTEP=3
        GO TO 350
C
C  LINE WITH 'HOST STATUS'
C
650     IF (ISTEP.NE.3) GO TO 875
        ISTEP=4
        HCOUNT=0
        GO TO 350
C
C  LINE WITH 'LINK STATUS'
C
700     IF (ISTEP.NE.4) GO TO 880
        ISTEP=5
        LCOUNT=0
        GO TO 350
C
C  NO MATCH WITH PRIMARY COMMANDS
C  RESCAN THE LINE FOR POSSIBLE STRING 'OUT OF PASSTHROUGHS'
C
750     TABLE(1)=9
        CALL CMND(-3,ICHAR,NUM)
        IF (NUM.NE.1) GO TO 752
        NSTATE=1
        GO TO 350
752     TABLE(1)=1
        IF (ISTEP.NE.4) GO TO 755
C
C  RETRIEVE HERE INFORMATION ABOUT HOSTS
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 875
        CALL CMND(-4,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 875
        HCOUNT=HCOUNT+1
        IHOST(HCOUNT)=INT
        HSTATE(HCOUNT)='ANSW'
        IF (NUM.EQ.2) HSTATE(HCOUNT)='SHUT'
        IF (NUM.EQ.3) HSTATE(HCOUNT)='DOWN'
        IF (NUM.EQ.4) HSTATE(HCOUNT)='OUT '
        IF (NUM.EQ.5) HSTATE(HCOUNT)='NO   '
        GO TO 350
755     IF (ISTEP.NE.5) GO TO 845
C
C  RETRIEVE INFORMATION ABOUT LINES
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 880
        IF (INT.NE.LCOUNT) GO TO 880
        CALL OCTAL(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 880
        LCOUNT=LCOUNT+1
        NEIGH(LCOUNT)=INT
        IF (NODENO.GE."2000) GO TO 760
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 880
        NGRPS(LCOUNT)=INT
        GO TO 765
760     NGRPS(LCOUNT)='?'
765     CALL CMND(-6,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 880
        IBAUD(LCOUNT)=ICHAR
C
C  LOOK FOR SPECIAL LINE CONDITION
        CALL CMND(-5,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 350
        IF (NUM.NE.6.AND.NUM.NE.7) GOTO 350
        LSTATE(LCOUNT)=ICHAR
        IF (NUM.EQ.1) GO TO 780
        GO TO 350
C
C  SPECIAL PATCH PUT ON OCT 3RD FOR 'OUT OF CHANNELS' STRING
780     TABLE(1)=TABLE(1)+4
        CALL CMND(-5,ICHAR,NUM)
        IF (NUM.NE.3) GO TO 350
        LSTATE(LCOUNT)='OFC'
        GO TO 350
C
C  ABNORMAL CONDITIONS WHILE USING COMMAND-10
C
845     TYPE 847
847     FORMAT(' SOMETHING GOES WRONG IN USING COMMAND-10')
        GO TO 2000
850     TYPE 852
852     FORMAT(' ERROR IN INTERPRETIND LINE ''NODE NUMBER''')
        GO TO 2000
855     TYPE 857
857     FORMAT(' ERROR IN INTERPRETING LINE ''NO SUCH NODE''')
        GO TO 2000
860     TYPE 862
862     FORMAT(' ERROR IN INTERPRETING LINE ''VERSION ...TYPE ...''')
        GO TO 2000
865     TYPE 867
867     FORMAT(' ERROR IN INTERPRETING LINE ''PORTS ...PASSTHROUGHS ...'
     X  '')
        GO TO 2000
870     TYPE 872
872     FORMAT(' ERROR IN INTERPRETING LINE ''AVAILABLE PASSTHROUGHS''')
        GO TO 2000
875     TYPE 877
877     FORMAT(' ERROR IN INTERPRETING LINES FOLLOWING ''HOST STATUS''')
        GO TO 2000
880     TYPE 882
882     FORMAT(' ERROR IN INTERPRETING LINES FOLLOWING ''LINE STATUS''')
        GO TO 2000
885     TYPE 887
887     FORMAT(' OUTPUT FROM PROBE EXCEEDS 72 CHARS PER LINE')
        GO TO 2000
890     ENCODE(4,154,ITMP) NODENO
        DECODE(4,155,ITMP) NODNO
        WRITE(ID,892) NODNO
892     FORMAT(///1X,'NO SUCH NODE ',I4,' ACCORDING TO PROBE')
        CLOSE(UNIT=20)
        GO TO 151
C
C  THIS PORTION UNTIL STM 915 IS USED ONLY IF NODENO GE "2000
C
895     IF (NTYP.NE.9) GO TO 915
        CLOSE(UNIT=20)
        OPEN(UNIT=21,FILE=IOFILE,ACCESS='SEQOUT',MODE='ASCII')
        IPOS=1
C
C  SEND OUT THE 'NEIGHBOR 2XXX' COMMAND
        CALL SEND(NBOR)
900     CALL WAIT(1.0)
902     CALL GTCHAR(PORT,CHAR)
        IF (CHAR.LT.0) GO TO 900
        CHAR=IAND(CHAR,127)
        IF (CHAR.EQ.COLON) GO TO 905
        IF (CHAR.EQ.CR) GO TO 904
        IF (CHAR.EQ.LF) GO TO 902
        CHAR=LSH(CHAR,29)
        ILINE(IPOS)=CHAR
        IPOS=IPOS+1
        GO TO 902
904     IPOS=IPOS-1
        WRITE(21,341) (ILINE(I),I=1,IPOS)
        IPOS=1
        GO TO 902
905     CLOSE(UNIT=21)
        ASSIGN 915 TO TABLE(8)
        OPEN(UNIT=20,FILE=IOFILE,ACCESS='SEQIN',MODE='ASCII')
C
C  INTERPRET OUTPUT FROM 'NEIGHBOR' COMMAND
907     CALL NEWLIN
        CALL OCTAL(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 913
        IF (INT.GE."2000) GO TO 907
        DO 908 I=1,LCOUNT
        IF (NEIGH(I).EQ.INT) GO TO 910
908     CONTINUE
        TYPE 909,INT,NODENO
909     FORMAT(/1X,'NEIGHBOR ',O4,' WAS NOT PRESENT IN ''N'' COMMAND',
     X  ' OF ',O4)
        GO TO 907
910     CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 913
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 913
        IF (INT.GT.0) NGRPS(I)=INT
        GO TO 907
913     TYPE 914
914     FORMAT(' ERROR IN INTERPRETING OUTPUT OF ''NEIGHBOR'' COMMAND')
        GO TO 2000
C
C  TRY TO READ NODE NAMES FROM 'NETCON.MAP'
C
915     CLOSE(UNIT=20)
        IF (NODENO.LT."3500.AND.NODNAM(1,NODENO).NE.0) GO TO 920
        NNAME(1)='?????'
        GO TO 922
920     NNAME(1)=NODNAM(1,NODENO)
        NNAME(2)=NODNAM(2,NODENO)
C
C  PAD BLANKS IN NODE NAME TO HAVE NICE FORMAT
        DO 921 I=10,1,-1
        IJ=I
        CALL RTC(ICHAR,NNAME,IJ)
        IF (ICHAR.NE.NULL) GO TO 922
        CALL STC(' ',NNAME,IJ)
921     CONTINUE
922     DO 930 I=1,LCOUNT
        ITMP=NEIGH(I)
        IF (ITMP.LE.0.OR.ITMP.GE."3500) GO TO 926
        IF (NODNAM(1,ITMP).EQ.0) GO TO 926
        NEINAM(I,1)=NODNAM(1,ITMP)
        NEINAM(I,2)=NODNAM(2,ITMP)
C
C  PAD BLANKS IN NEINAM
        DO 923 J=5,1,-1
        IJ=J
        CALL RTC(ICHAR,NEINAM(I,2),IJ)
        IF (ICHAR.NE.NULL) GO TO 930
        CALL STC(' ',NEINAM(I,2),IJ)
923     CONTINUE
        DO 925 J=5,1,-1
        IJ=J
        CALL RTC(ICHAR,NEINAM(I,1),IJ)
        IF (ICHAR.NE.NULL) GO TO 930
        CALL STC(' ',NEINAM(I,1),IJ)
925     CONTINUE
926     NEINAM(I,1)='?????'
930     CONTINUE
C
C  NOW READ CIRCUIT NAMES FROM 'PLOT.LIN'
C
        CALL DBOPEN(LFILE)
        CALL DBFIND('ALL')
        ENCODE(4,154,ITMP) NODENO
        DECODE(4,155,ITMP) NODNO
        DO 945 I=1,LCOUNT
        ITMP=NEIGH(I)
        IF (ITMP.LE.0) GO TO 931
        ENCODE(4,154,ITEMP) ITMP
        DECODE(4,155,ITEMP) ITMP
        NNEIGH(I)=ITMP
        CALL DBFIND('NOD1','EQ',NODNO,'AND','NOD2','EQ',ITMP,'SAV.',1,
     X  'NOD2','EQ',NODNO,'AND','NOD1','EQ',ITMP,'OR','REF.',1)
        CALL DBNREC(IREC)
        IF (IREC.GE.1) GO TO 935
931     LINE(I,1)='?????'
        GO TO 945
935     CALL DBGREC($945)
        CALL DBVAL('NAME',LNAM)
        DO 940 J=1,4
        LINE(I,J)=LNAM(J)
940     CONTINUE
945     CONTINUE
        CALL DBCLOS
C
C  THIS PORTION OF CODE UNTIL STM 1900 HAS BEEN ADDED
C  ON JANUARY 22ND, 1981 TO RETRIEVE NODE TYPE FOR NEIGHBORS
C
        OPEN(UNIT=22,FILE=JOFILE,ACCESS='SEQOUT',MODE='ASCII')
        DO 1000 I=1,LCOUNT
        WRITE(22,155) NNEIGH(I)
1000    CONTINUE
        CLOSE(UNIT=22)
        OPEN(UNIT=22,FILE=JOFILE,ACCESS='SEQIN',MODE='ASCII')
        ICTR=0
1002    READ(22,154,END=1900) NODENO
        ICTR=ICTR+1
        IF (NODENO.GE."2000) GO TO 1125
C
        OPEN(UNIT=21,FILE=IOFILE,ACCESS='SEQOUT',MODE='ASCII')
        IPOS=1
        IF (NODENO.GE."10) GO TO 1005
C
        REREAD 1003,NODNUM(1)
1003    FORMAT(3X,A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        N(1)=4
        N(5)=13
        N(4)=NODNUM(1)
        WRITE(21,293) NODENO
        GO TO 1020
1005    IF (NODENO.GE."100) GO TO 1010
C
        REREAD 1006,(NODNUM(I),I=1,2)
1006    FORMAT(2X,2A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        N(1)=5
        N(6)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        WRITE(21,296) NODENO
        GO TO 1020
1010    IF (NODENO.GE."1000) GO TO 1015
C
        REREAD 1011,(NODNUM(I),I=1,3)
1011    FORMAT(1X,3A1)
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        NODNUM(3)=LSH(NODNUM(3),-29)
        N(1)=6
        N(7)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        N(6)=NODNUM(3)
        WRITE(21,306) NODENO
        GO TO 1020
C
1015    REREAD 315,(NODNUM(I),I=1,4)
        NODNUM(1)=LSH(NODNUM(1),-29)
        NODNUM(2)=LSH(NODNUM(2),-29)
        NODNUM(3)=LSH(NODNUM(3),-29)
        NODNUM(4)=LSH(NODNUM(4),-29)
        N(1)=7
        N(8)=13
        N(4)=NODNUM(1)
        N(5)=NODNUM(2)
        N(6)=NODNUM(3)
        N(7)=NODNUM(4)
        WRITE(21,316) NODENO
C
1020    CALL SEND(N)
C
1030    CALL WAIT(1.0)
1035    CALL GTCHAR(PORT,CHAR)
        IF (CHAR.LT.0) GO TO 1030
        CHAR=IAND(CHAR,127)
C
        IF (CHAR.EQ.COLON) GO TO 1045     IF (CHAR.EQ.CR) GO TO 1040
        IF (CHAR.EQ.LF) GO TO 1035
        CHAR=LSH(CHAR,29)
        ILINE(IPOS)=CHAR
        IPOS=IPOS+1
        GO TO 1035
1040    IPOS=IPOS-1
        WRITE(21,341) (ILINE(I),I=1,IPOS)
        IPOS=1
        GO TO 1035
C
1045    CLOSE(UNIT=21)
        ISTEP=0
        OPEN(UNIT=20,FILE=IOFILE,ACCESS='SEQIN',MODE='ASCII')
        ASSIGN 1130 TO TABLE(8)
C
1050    CALL NEWLIN
C
        CALL CMND(-1,ICHAR,NUM)
        IF (NUM.NE.1.AND.NUM.NE.2.AND.NUM.NE.3) GO TO 1002
        GO TO (1100,1110,1120) NUM
C
1100    IF (ISTEP.NE.0) GO TO 850
        ISTEP=1
        CALL OCTAL(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 850
        IF (INT.NE.NODENO) GO TO 850
        GO TO 1050
C
1110    IF (ISTEP.NE.1) GO TO 855
        CALL CMND(-7,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 855
        ISTEP=0
        NEITYP(ICTR)='?'
        CLOSE(UNIT=20)
        GO TO 1002
C
1120    IF (ISTEP.NE.1) GO TO 860
        ISTEP=2
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 860
        CALL CMND(-2,ICHAR,NUM)
        IF (NUM.LE.0) GO TO 860
        CALL INTGR(INT,ISTAT)
        IF (ISTAT.NE.1) GO TO 860
        IF (INT.GE.9) GO TO 860
        NEITYP(ICTR)=INT
        CLOSE(UNIT=20)
        GO TO 1002
C
1125    NEITYP(ICTR)=9
        GO TO 1002
C
1130    CLOSE(UNIT=20)
        CLOSE(UNIT=22)
        TYPE 1132
1132    FORMAT(' SOMETHING GOES WRONG WHILE RETRIEVING NODE TYPES',
     X  ' FOR NEIGHBORS')
        GO TO 2000
C
C  NOW READY TO OUTPUT ALL INFORMATION ABOUT NODE
C
1900    CLOSE(UNIT=22)
        CALL DATE(IXDTE)
        CALL TIME(ITIME)

        WRITE(ID,1951) IXDTE,ITIME
1951    FORMAT(//,27X,2A5,' ; ',A5)
        WRITE(ID,1952)
1952     FORMAT(/1X,'NODE NO.  &NAME',10X,'TYPE',7X,'VERSION',7X,
     X  'STATE',7X,'# NEIGH',/1X,15('*'),/)
        IF (NSTATE.EQ.1) WRITE(ID,1960) NODNO,(NNAME(I),I=1,2),NTYP,
     X  IVERS,LCOUNT
        IF (NSTATE.EQ.0) WRITE(ID,1961) NODNO,(NNAME(I),I=1,2),NTYP,
     X  IVERS,LCOUNT
1960     FORMAT(2X,I4,4X,2A5,8X,I1,7X,I7,4X,'OUT OF PASSTHR',4X,I2)
1961     FORMAT(2X,I4,4X,2A5,8X,I1,7X,I7,9X,'UP',11X,I2)
        WRITE(ID,1962)
1962     FORMAT(/1X,'NEIGHBOR DETAILS',/1X,16('-'))
        WRITE(ID,1964)
1964     FORMAT(2X,'#',3X,'LINE NAME',11X,'NEIGH',7X,'NAME',4X,
     X  '# GRPS',4X,'SPEED',4X,'TYPE')
        DO 1970 I=1,LCOUNT
        ITMP=I-1
1966    IF (NGRPS(I).EQ.'?') GO TO 1968
        IF (NEITYP(I).NE.'?') WRITE(ID,1967) ITMP,(LINE(I,J),J=1,4),
     X  NNEIGH(I),NEITYP(I),(NEINAM(I,J),J=1,2),NGRPS(I),
     X  IBAUD(I),LSTATE(I)
1967    FORMAT(1X,I2,2X,4A5,1X,I4,'(',I1,')',3X,2A5,3X,I1,7X,A4,5X,A5)
        IF (NEITYP(I).EQ.'?') WRITE(ID,1867) ITMP,(LINE(I,J),J=1,4),
     X  NNEIGH(I),NEITYP(I),(NEINAM(I,J),J=1,2),NGRPS(I),
     X  IBAUD(I),LSTATE(I)
1867    FORMAT(1X,I2,2X,4A5,1X,I4,'(',A1,')',3X,2A5,3X,I1,7X,A4,5X,A5)
        GO TO 1970
1968    IF (NEITYP(I).NE.'?') WRITE(ID,1969) ITMP,(LINE(I,J),J=1,4),
     X  NNEIGH(I),NEITYP(I),(NEINAM(I,J),J=1,2),NGRPS(I),
     X  IBAUD(I),LSTATE(I)
1969    FORMAT(1X,I2,2X,4A5,1X,I4,'(',I1,')',3X,2A5,3X,A1,7X,A4,5X,A5)
        IF (NEITYP(I).EQ.'?') WRITE(ID,1869) ITMP,(LINE(I,J),J=1,4),
     X  NNEIGH(I),NEITYP(I),(NEINAM(I,J),J=1,2),NGRPS(I),
     X  IBAUD(I),LSTATE(I)
1869    FORMAT(1X,I2,2X,4A5,1X,I4,'(',A1,')',3X,2A5,3X,A1,7X,A4,5X,A5)
1970     CONTINUE
        IF (NODNO.GE.1000.AND.NODNO.LT.2000) GO TO 1978
        WRITE(ID,1972)
1972     FORMAT(/1X,'HOST DETAILS',/1X,12('-'))
        WRITE(ID,1974)
1974     FORMAT(26X,'HOST NO',3X,'STATE')
        DO 1990 I=1,HCOUNT
        WRITE(ID,1977) IHOST(I),HSTATE(I)
1977     FORMAT(27X,I4,6X,A5)
1990     CONTINUE
1978     WRITE (ID,1979)
1979     FORMAT(//1X,'DO YOU WANT THE PLOT ?',$)
        READ (5,1980,ERR=1978) IRESP
1980     FORMAT(A1)
        IF (IRESP.EQ.'N') GOTO 151
        IF (IRESP.NE.'Y') GOTO 1978
C
C       SET THE ARGUMENTS FOR THE SUBROUTINE DRANOD
C
        NONOD(1)=NODNO
        NTYPE(1)=NTYP
        INONA(1,1)=NNAME(1)
        INONA(1,2)=NNAME(2)
        DO 1982 I=1,LCOUNT
        J=I+1
        NONOD(J)=NNEIGH(I)
        NTYPE(J)=NEITYP(I)
        DO 1981 K=1,2
        INONA(J,K)=NEINAM(I,K)
1981     CONTINUE
1982     CONTINUE

        DO 1991 I=1,LCOUNT
        ITEMP=IBAUD(I)
        CALL RTC(ICHAR,ITEMP,1)
        IF (ICHAR.EQ.'M') GOTO 1988
        ITEMP=LINE(I,1)
        CALL RTC(ICHAR,ITEMP,1)
        IF (ICHAR.NE.'H') GOTO 1984
        CALL RTC(ICHAR,ITEMP,2)
        IF (ICHAR.NE.'W') GOTO 1984
1984    ITEMP=LSTATE(I)
        CALL RTC(ICHAR,ITEMP,1)
        IF (ICHAR.EQ.'W') GOTO 1985
        IF (ICHAR.EQ.'S') GOTO 1987
        GOTO 1986
1985    NLTYP(I)=1
        GOTO 1991
1986    NLTYP(I)=2
        GOTO 1991
1987    NLTYP(I)=3
        GOTO 1991
1988    NLTYP(I)=4
1991     CONTINUE

C
C       CALL THE PLOTTING SUBROUTINE
C
        CALL DRANOD(LCOUNT,NONOD,NTYPE,IVERS,INONA,
     -NLTYP,LINE,NGRPS,IBAUD,HCOUNT,IHOST)

        GO TO 151
C
C  FINISHED !!
C
2000    CALL DBEND
        CALL SEND(KILL)
        CLOSE(UNIT=20)
        CLOSE(UNIT=21)
        CLOSE(UNIT=22)
        CLOSE(UNIT=23)
        END

        SUBROUTINE SCAN(TARGET,RESULT)
        INTEGER TARGET,RESULT,PORT,DELAYC,CHAR
        COMMON /PRBE/PORT
C
C  SEARCH FOR TARGET CHARACTER
C  ALLOW ONLY A LIMITED DELAY
C
        DELAYC=0
10      CALL GTCHAR(PORT,CHAR)
        IF (CHAR.GE.0) GO TO 20
C
C  SLEEP A LITTLE
C
        RESULT=2
        CALL WAIT(2.0)
        DELAYC=DELAYC+1
        IF (DELAYC.GE.10) RETURN
        GO TO 10
C
C  WE GOT A CHAR, IS IT THE ONE WE WANT
C
20      CHAR=IAND(CHAR,127)
        RESULT=1
        IF (CHAR.EQ.TARGET) RETURN
        GO TO 10
        END

        SUBROUTINE SEND(OUTPUT)
        INTEGER OUTPUT(1),PORT
        COMMON /PRBE/PORT

        J=OUTPUT(1)+1
        DO 10 I=2,J
        CALL OUTCHR(PORT,OUTPUT(I))
10      CONTINUE
        RETURN
        END
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
C               SUBROUTINE DRANOD
C
C       THIS SUBROUTINE PLOT THE TOPOLOGY OF
C       ONE GIVEN NODE WITH THE DATA RETRIEVED
C       FROM PROBE
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC


        SUBROUTINE DRANOD(NODNUM,NUMNOD,NTYPE,NVERS,
     -NNODE,LTYPE,NLINE,NGRPS,IBDS,HOSNUM,HOSNAM)

        DIMENSION XARAY(100),YARAY(100),XO(33),YO(33)
        DIMENSION XCUR(2),YCUR(2),HEX(7),HEY(7),RECX(5),RECY(5)
        INTEGER NLINE(32,4),LTYPE(32),NUMNOD(33),NTYPE(33)
     -,NVERS(33),IBDS(32),ITEXT(3,10),NGRPS(32),HOSNAM(16)
     -,IXDTE(2)
     -,NNODE(33,2),HOSNUM
        DATA HEX/4.,2.5,-2.5,-4.,-2.5,2.5,4./
        DATA HEY/0.,1.8,1.8,0.,-1.8,-1.8,0./
        DATA RECX/4.,-4.,-4.,4.,4./
        DATA RECY/1.3,1.3,-1.3,-1.3,1.3/
        ITEXT(1,1)='REMOT'
        ITEXT(2,1)='E    '
        ITEXT(3,1)='     '
        ITEXT(1,2)='BASE '
        ITEXT(2,2)='(PDP-'
        ITEXT(3,2)='10)  '
        ITEXT(1,3)='DUAL '
        ITEXT(2,3)='BASE '
        ITEXT(3,3)='(940)'
        ITEXT(1,4)='SUPER'
        ITEXT(2,4)=' REMO'
        ITEXT(3,4)='TE   '
        ITEXT(1,5)='SBASE'
        ITEXT(2,5)=' (1 H'
        ITEXT(3,5)='OST) '
        ITEXT(1,6)='SBASE'
        ITEXT(2,6)=' (2 H'
        ITEXT(3,6)='OSTS)'
        ITEXT(1,7)='SBASE'
        ITEXT(2,7)=' (3,4'
        ITEXT(3,7)=' HST)'
        ITEXT(1,8)='ENGIN'
        ITEXT(2,8)='E REM'
        ITEXT(3,8)='OTE  '
        ITEXT(1,9)='ENGIN'
        ITEXT(2,9)='E SWI'
        ITEXT(3,9)='TCHER'
        ITEXT(1,10)='TYMNE'
        ITEXT(2,10)='T II '
        ITEXT(3,10)='     '
C
C       SET THE PLOTTING AREA
C
        CALL TEK(120,1)
        CALL PAGE(16.,12.)
        CALL NOBRDR
        CALL PHYSOR(1.5,0.5)
        CALL TITLE('TOPOLOGY OF NODE $',100,
     -' $',100,' $',100,12.7,10.)
        CALL XAXEND('NOENDS')
        CALL YAXEND('NOENDS')
        CALL XTICKS(0)
        CALL YTICKS(0)
        CALL GRAF(-27.,1000.,100.,0.,1000.,100.)
C
C       PLOT VARIOUS MESSAGES AND DATA
C
        CALL HEIGHT(0.2)
        CALL RLINT(NUMNOD(1),52.,106.1)
        CALL DATE(IXDTE)
        CALL TIME(ITIME)
        DO 333 INCHR=10,1,-1
        IJ=INCHR
        CALL RTC(ICHAR,IXDTE,IJ)
        IF (ICHAR.NE.' ') GOTO 334
333     CONTINUE
334     CALL RLMESS(IXDTE(1),5,24.,102.)
        CALL RLMESS(IXDTE(2),INCHR-6,'ABUT','ABUT')
        CALL RLMESS(' ; ',3,'ABUT','ABUT')
        CALL RLMESS(ITIME,5,'ABUT','ABUT')
        CALL RLMESS('TYPE : $',100,-24.,88.)
        CALL RLINT(NTYPE(1),'ABUT','ABUT')
        CALL RLMESS(' -',2,'ABUT','ABUT')
        IDX=NTYPE(1)+1
        CALL RLMESS(ITEXT(1,IDX),5,'ABUT','ABUT')
        CALL RLMESS(ITEXT(2,IDX),5,'ABUT','ABUT')
        CALL RLMESS(ITEXT(3,IDX),5,'ABUT','ABUT')
        CALL RLMESS('CODE VERSION :$',100,-24.,81.)
        CALL RLINT(NVERS(1),'ABUT','ABUT')
        CALL RLMESS('NUMBER OF NEIGHBOURS :$',100,-24.,95.)
        CALL RLINT(NODNUM,'ABUT','ABUT')
        IF (HOSNUM.EQ.0) GOTO 8
        CALL RLMESS('HOST NUMBER :$',100,-24.,74.)
        DO 1 I=1,HOSNUM
        YPOTEM=74.-(I*7.)
        CALL RLINT(HOSNAM(I),-24.,YPOTEM)
1       CONTINUE
C
C       PLOT INFORMATION FOR LINE SYMBOLS
C
8       CALL STRTPT(0.25,1.9)
        CALL CONNPT(1.75,1.9)
        CALL RLMESS(': WINDOW SIZE 4$',100,-8.,19.)
        CALL DASH
        CALL STRTPT(0.25,1.2)
        CALL CONNPT(1.75,1.2)
        CALL RLMESS(': WINDOW SIZE 8$',100,-8.,12.)
        CALL CHNDSH
        OFFSET=0.01
        DO 2 I=1,3
        CALL MOVCRV(OFFSET)
        XCUR(1)=-25.
        YCUR(1)=26.
        XCUR(2)=-10.
        YCUR(2)=26.
        CALL CURVE(XCUR,YCUR,2,0)
        OFFSET=OFFSET+0.01
2       CONTINUE
        CALL RESET('MOVCRV')
        CALL RLMESS(': SATELLITE$',100,-8.,26.)
        CALL RESET('DASH')
        CALL RESET('CHNDSH')
        OFFSET=0.01
        DO 3 I=1,5
        CALL MOVCRV(OFFSET)
        YCUR(1)=5.
        YCUR(2)=5.
        CALL CURVE(XCUR,YCUR,2,0)
        OFFSET=OFFSET+0.01
3       CONTINUE
        CALL RESET('MOVCRV')
        CALL RLMESS(': MEMORY SHUFFLER$',100,-8.,5.)
        OFFSET=0.

        CALL RESET('HEIGHT')
C
C       DRAW NODES AND LINES
C
        XO(1)=50.
        YO(1)=50.

        IMAX=NODNUM+1
        DO 5 I=2,IMAX
        XO(I)=XO(1)+40.*COS(6.283*(FLOAT(2-I)/NODNUM)+1.571)
        YO(I)=YO(1)+40.*SIN(6.283*(FLOAT(2-I)/NODNUM)+1.571)
5       CONTINUE

        DO 100 I=1,IMAX

        IF(NTYPE(I).EQ.0) GOTO 6
        IF(NTYPE(I).EQ.3) GOTO 6
        IF (NTYPE(I).LT.7) GOTO 11
        
6       IF (NTYPE(I).LT.9) GOTO 7
        IF (NUMNOD(I).GT.2005) GOTO 13
        GOTO 18

7       DO 10 T=1,100
        XARAY(T)=XO(I)+4.*COS(T*0.0628)
        YARAY(T)=YO(I)+1.3*SIN(T*0.0628)
10      CONTINUE

        CALL CURVE(XARAY,YARAY,100,0)
        GOTO 25

11      DO 12 T=1,7
        XARAY(T)=XO(I)+HEX(T)
        YARAY(T)=YO(I)+HEY(T)
12      CONTINUE
        CALL CURVE(XARAY,YARAY,7,0)
        GOTO 25

13      DO 14 T=1,100
        XARAY(T)=XO(I)+4.*COS(T*0.0628)
        YARAY(T)=YO(I)+1.3*SIN(T*0.0628)
14      CONTINUE
        CALL CURVE(XARAY,YARAY,100,0)
        CALL MOVCRV(0.07)
        CALL CURVE(XARAY,YARAY,100,0)
        CALL RESET('MOVCRV')
        GOTO 25

18      DO 19 T=1,5
        XARAY(T)=XO(I)+RECX(T)
        YARAY(T)=YO(I)+RECY(T)
19      CONTINUE
        CALL CURVE(XARAY,YARAY,5,0)
        CALL MOVCRV(0.07)
        CALL CURVE(XARAY,YARAY,5,0)
        CALL RESET('MOVCRV')

C
C       PLOT NODE NUMBER AND NAME
C
25      CALL HEIGHT(0.1)
        XPOS=XO(I)-2.95
        YPOS=YO(I)-0.55
        CALL RLMESS(NNODE(I,1),5,XPOS,YPOS)
        CALL RLMESS(NNODE(I,2),5,'ABUT','ABUT')
        CALL RESET('HEIGHT')
        CALL RLINT(NUMNOD(I),XO(I)-1.6,YO(I)+2.5)

        IF (I.EQ.IMAX) GOTO 100

        X1=XO(1)+5.*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y1=YO(1)+5.*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        X2=XO(1)+35.*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y2=YO(1)+35.*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        X3=XO(1)+10.*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y3=YO(1)+10.*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        X5=XO(1)+12.5*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y5=YO(1)+12.5*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)

        XI1=12.7*((X1+27.)/127.)
        YI1=10.*(Y1/100.)
        XI2=12.7*((X2+27.)/127.)
        YI2=10.*(Y2/100.)
        XI4=-0.1*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        YI4=0.1*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)

        IF (LTYPE(I).GT.1) GOTO 29
        CALL DASH
        GOTO 90
29      IF (LTYPE(I).GT.2) GOTO 31
        CALL RESET('DOT')
        CALL RESET('DASH')
        CALL RESET('CHNDOT')
        CALL RESET('CHNDSH')
        GOTO 90
31      IF (LTYPE(I).GT.3) GOTO 32
        OFFSET=-0.01
        CALL CHNDSH
        DO 71 J=1,3
        IF (OFFSET.EQ.0.) GOTO 70
        CALL MOVCRV(OFFSET)
70      XCUR(1)=X1
        XCUR(2)=X2
        YCUR(1)=Y1
        YCUR(2)=Y2
        CALL CURVE(XCUR,YCUR,2,0)
        CALL RESET('MOVCRV')
        OFFSET=OFFSET+0.01
71      CONTINUE
        GOTO 90
32      OFFSET=-0.02
        DO 33 J=1,5
        IF (OFFSET.EQ.0.) GOTO 44
        CALL MOVCRV(OFFSET)
44      XCUR(1)=X1
        YCUR(1)=Y1
        XCUR(2)=X2
        YCUR(2)=Y2
        CALL CURVE(XCUR,YCUR,2,0)
        OFFSET=OFFSET+0.01
33      CONTINUE

90     CALL STRTPT(XI1,YI1)
        CALL CONNPT(XI2,YI2)
        CALL RESET('DOT')
        CALL RESET('DASH')
        CALL RESET('CHNDOT')
        CALL RESET('CHNDSH')

C
C       PLOT MESSAGE FOR EACH LINE AT THE RIGHT ANGLE
C
        XANG=(360.*(FLOAT(1-I)/NODNUM)+90.)
        IF (XANG.LT.-630) GOTO 95
        IF (XANG.LT.-450) GOTO 94
        IF (XANG.LT.-270.) GOTO 95
        IF (XANG.LT.-90.) GOTO 94
        GOTO 95
94      X3=X3+20.*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y3=Y3+20.*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        X5=X5+15.*COS(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        Y5=Y5+15.*SIN(6.283*(FLOAT(1-I)/NODNUM)+1.571)
        XANG=XANG+180.
        TEMP=-XI4
        XI4=TEMP
        TEMP=-YI4
        YI4=TEMP
95      CALL ANGLE(XANG)
        CALL MSHIFT(XI4,YI4)
        CALL RLMESS(NLINE(I,1),5,X3,Y3)
        CALL RESET('MSHIFT')
        CALL RLMESS(NLINE(I,2),5,'ABUT','ABUT')
        CALL RLMESS(NLINE(I,3),5,'ABUT','ABUT')
        CALL RLMESS(NLINE(I,4),5,'ABUT','ABUT')
        TEMP=-(2*XI4)
        XI4=TEMP
        TEMP=-(2*YI4)
        YI4=TEMP
        CALL MSHIFT(XI4,YI4)
        ITEMP=IBDS(I)
        CALL RTC(ICHAR,ITEMP,1)
        IF ((ICHAR.NE.'M').AND.(ICHAR.NE.'5')) GOTO 97
        CALL RLMESS(IBDS(I),2,X5,Y5)
        GOTO 98
97      IF (ICHAR.EQ.'1') CALL RLMESS(IBDS(I),4,X5,Y5)
        IF (ICHAR.EQ.'1') GOTO 98
        CALL RLMESS(IBDS(I),3,X5,Y5)
98      CALL RESET('MSHIFT')
        IF (NGRPS(I).EQ.'?') GOTO 99
        CALL RLMESS(';($',100,'ABUT','ABUT')
        CALL RLINT(NGRPS(I),'ABUT','ABUT')
        CALL RLMESS(' GRPS)$',100,'ABUT','ABUT')
99      CALL RESET('ANGLE')

100     CONTINUE

                HOSNUM=0
C
C       FRAME THIS PLOT AND LET THE USER CLEAR THE SCREEN
C       WHEN HE HITS A CARRIAGE RETURN
C

        CALL FRAME
        CALL ENDPL(0)
        CALL PAGE(12.7,10.)
        CALL PHYSOR(3.,0.5)
        CALL TITLE(' $',100,' $',100,' $',100,12.7,10.)

        RETURN
        END
*       *************** SUBROUTINE CONVRT ********************


*       THIS SUBROUTINE CONVERTS A OCTAL NUMBER (4-DIGITS OR LESS)
*       INTO AN DECIMAL NUMBER

        SUBROUTINE CONVRT(OCT,DEC)

        INTEGER DEC,OCT,TMP(6)

        TMP(1)=OCT
        DO 50 I=1,5
        TMP(I+1)=TMP(I)/10
        TMP(I)=MOD(TMP(I),10)
50      CONTINUE

        DEC=(((TMP(5)*8+TMP(4))*8+TMP(3))*8+TMP(2))*8+TMP(1)
        RETURN
        END


   BXn‹