
++++ PLEASE DO NOT DELETE OR WRITE OVER THIS FILE..THANK-YOU ++++



TO: PROJECT PARTS
FR: LARRY MACEK
RE: PARTS RECIEVED
PR: 48920.033

**********************************************************************


        FFFFFFFF      OOOOOO      RRRRRRR      DDDDDDD
        FFFFFF       OOOOOOOO     RRRRRRRR     DDDDDDDD
        FFF          OOO  OOO     RRR  RRR     DDD  DDD
        FFF          OOO  OOO     RRR  RRR     DDD  DDD
        FFFFF        OOO  OOO     RRRRRRR      DDD  DDD
        FFF          OOO  OOO     RRRRR        DDD  DDD
        FFF          OOO  OOO     RRR RR       DDD  DDD
        FFF          OOOOOOOO     RRR  RR      DDDDDDDD
        FFF           OOOOOO      RRR   RR     DDDDDDD

************************************************************************


THE FOLLOWING PARTS HAVE BEEN RECIEVED FOR ORDER 48920.033 AT
JACKSON BLVD., CHICAGO:


-----------------------------------------------------------------------

QTY   PART NUMBER    SERIAL NUMBER   ASSET NUMBER  DESCRIPTION
------------------------------------------------------------------------
01    470123-001     J161231         N/A           ABC- SIO
01    470212-001     J0159064        N/A           ABC- 4 CHANNEL SYNC
01    470214-001     J0161501        N/A           ABC- 8 CHANNEL OCL
01    160182-502     N/A             N/A           CABLE, CONTROL CARD
01    160157-501     N/A             N/A           CABLE, 50 PIN BREAKOUT SYNC
01    160177-001     N/A             N/A           CABLE, OCL BREAKOUT
01    160054-004     N/A             N/A           CABLE, OCL X-OVER





:SEND ** PROJPARTS L/MACEK S/MILLER
