++++ PLEASE DO NOT DELETE OR WRITE OVER THIS FILE...THANK-YOU ++++


TO: PROJPARTS
FR: LARRY MACEK/ ENFE.CH
RE: PARTS RECIEVED
PR: 49607.004



THE FOLLOWING PARTS HAVE BEEN RECIEVED AT JACKSON BLVD. , CHICAGO, ILL:


-------------------------------------------------------------------------------
QTY   PART NUMBER    SERIAL NUMBER   ASSET NUMBER   DESCRIPTION
------------------------------------------------------------------------------

02    600028-001     9027            257734         MODEM, PDY MP9600
                     3222            240094                "
------------------------------------------------------------------------------
02    160110-062     N/A             N/A            CABLE...DB25



------------------------------------------------------------------------------

:SEND ** PROJPARTS L/MACEK S/MILLER

